function infoB()
  figure('Name','Info Class B',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.8 0.8],...
    'Color',[0.3 0.9 0.3]); 

label_meniu();

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.3 0.90 0.3 .075],...
    'backgroundcolor',[0.3 0.9 0.3],...
    'string','Class B','FontSize',22);

w = imread('infoB1.jpg'); %reads the picture% 
subplot('position',[0.03 0.22 0.45 0.65]);
imshow(w,[]) %displays the picture%

w = imread('infoB2.jpg'); %reads the picture% 
subplot('position',[0.53 0.22 0.45 0.65]);
imshow(w,[]) %displays the picture%

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.1 0.08 .05],...
    'String','BACK',...
    'Callback','close;ClassB(50,5,3,3,0.7,10)');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.03 0.08 .05],...
    'String','CLOSE',...
    'Callback','close'); 
