f=50;
N=5;
Vcc=3;
Vtht=0.7;
Vthd=0.7;
A=3;
RL=10;

figure('Name','Power amplifiers',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.8 0.8],...
    'Color',[0.3 0.9 0.3]); 

w = imread('poza.jpg'); %reads the picture% 
subplot('position',[0.125 0.1 0.75 0.6]);
imshow(w,[]) %displays the picture

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.32 0.88 0.35 .075],...
    'backgroundcolor',[0.3 0.9 0.3],...
    'string','Power amplifiers','FontSize',30); 

label_meniu();
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.45 0.75 0.1 .1],...
    'backgroundcolor',[0.2 0.5 0.9],...
    'String','App','FontSize',18,...
    'Callback','close;Meniu(f,N,Vcc,Vtht,Vthd,A,RL)'); 

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.03 0.08 .05],...
    'backgroundcolor',[0.3 0.9 0.3],...
    'string','Vlad Veliciu');