function Meniu(f,N,Vcc,Vtht,Vthd,A,RL)
  figure('Name','Power amplifiers',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.8 0.8],...
    'Color',[0.3 0.9 0.3]); 

label_meniu();

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.3 0.70 0.3 .075],...
    'backgroundcolor',[0.3 0.9 0.3],...
    'string','Power amplifiers','FontSize',28); 

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.2 0.5 0.1 .1],...
    'String','Class B','Fontsize',18,...
    'Callback','close;ClassB(f,N,A,Vcc,Vtht,RL);'); 
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.4 0.5 0.1 .1],...
    'String','Class AB','Fontsize',18,...
    'Callback','close;ClassAB(f,N,A,Vcc,Vtht,Vthd,RL);'); 
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.6 0.5 0.1 .1],...
    'String','Info Power','Fontsize',14,...
    'Callback','close;Power()'); 

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.03 0.08 .05],...
    'String','CLOSE',...
    'Callback','close'); 